### ISSUE TITLE
Allow broadcasting of `Not`

### ISSUE THREAD

**Issue by bkamins** [JuliaData/InvertedIndices.jl#15]
In DataAPI.jl we consider allowing broadcasting of `All` and `Between`, https://github.com/JuliaData/DataAPI.jl/pull/10.

It would be great if also `Not` supported broadcasting.

@mbauman - would you be OK with such an addition?

**Comment by CameronBieganek** [comment]
+1

This would be really handy for DataFrames.jl. I'd like to be able to do this

```julia
select(df, Not(:x) .=> sum)
```

to sum every column except for `:x`.

**Comment by bkamins** [comment]
@mbauman - alternatively we could do some type piracy in DataAPI.jl and `Not` would have defined broadcasting behavior if that package were loaded (as currently `Not` is not broadcastable and I guess you do not have plans to make it broadcastable).

This is probably not a clean solution, but if you do not think it is worth to add the support for `Not` broadcasting here maybe this is a second best approach?

**Comment by bkamins** [comment]
@mbauman - could you please comment what is your preference here? The issue is popping up a lot recently. Thank you!

**Comment by mbauman** [comment]
Yes, this seems quite reasonable.
