### ISSUE TITLE
Allow out of bounds indices in Not

### ISSUE THREAD

**Issue by bkamins** [JuliaData/InvertedIndices.jl#17]
Originally posted at https://github.com/JuliaData/DataFrames.jl/issues/2197.

The question is should we allow the following code:
```
julia> x = [1,2,3]
3-element Array{Int64,1}:
 1
 2
 3

julia> x[Not(4)]
ERROR: BoundsError: attempt to access 3-element Array{Int64,1} at index [Not(4)]
```
to work (and in this case just return `[1,2,3]`) instead of throwing an error?

**Comment by mbauman** [comment]
Personally, I'm in favor of the status quo, but I agree the DataFrame column name feels different than an out-of-bounds index.

**Comment by bkamins** [comment]
OK - we can change it only for column names. Thank you!
