### ISSUE TITLE
Allow vararg form of `Not` for symbols

### ISSUE THREAD

**Issue by CameronBieganek** [JuliaData/InvertedIndices.jl#18]
Currently, `Not` has a vararg form which is equivalent to the normal form:

```julia
julia> x = 1:4;

julia> x[Not(2, 3)] == x[Not([2, 3])]
true
```

But this doesn't work for symbols:

```julia
julia> Not(:a, :b)
ERROR: MethodError: no method matching InvertedIndex(::Symbol, ::Symbol)
Closest candidates are:
  InvertedIndex(::S) where S
```

Since `Not([:a, :b])` is used for DataFrames.jl, it would be handy if `Not(:a, :b)` also worked.

**Comment by bkamins** [comment]
or in general that anything could be passed in a vararg form.

**Comment by pdeffebach** [comment]
I was going to file an issue here with the same request. @mbauman what do you think of a vararg constructor? Saves typing when working with literals.

**Comment by CameronBieganek** [comment]
> Saves typing when working with literals.

Yes, though I prefer to emphasize the improved readability over the reduced keystrokes. 😃

**Comment by mbauman** [comment]
Sure, this seems reasonable.

**Comment by CameronBieganek** [comment]
Bump.

**Comment by bkamins** [comment]
I guess you could open a PR for this. Would you be willing to?

**Comment by CameronBieganek** [comment]
Sure!

**Comment by ararslan** [comment]
This was implemented in https://github.com/JuliaData/InvertedIndices.jl/pull/36.
