### ISSUE TITLE
Does not provide the complement of the indices

### ISSUE THREAD

**Issue by hebertodelrio** [JuliaData/InvertedIndices.jl#19]
If you use the following code fragment:

```
using RDatasets
using StatsBase

iris = dataset("datasets", "iris")
ndx = sample(1:size(iris,1), Int64(0.1*size(iris,1)))

x = iris[ndx,:]
y = iris[Not(ndx),:]
```
 the x and y are not complement of each other, as they should

**Comment by mbauman** [comment]
You are `sample`ing with replacement, and thus `ndx` may contain a repeated index.  In such a case, `x` will have a repeated row and `y` will have more than `size(iris,1)-15` rows.  Is that what you're seeing?

**Comment by mbauman** [comment]
In short, you may be wanting to use `sample(1:size(iris,1), Int64(0.1*size(iris,1)), replace=false)`.

**Comment by hebertodelrio** [comment]
Thank you for the prompt response, that is certainly what I was doing!
Your suggestion is the appropriate.

 Thanks

-- 
Heberto del Rio

On May 5, 2020 at 2:38:25 PM, Matt Bauman (notifications@github.com) wrote:

In short, you may be wanting to use sample(1:size(iris,1),
Int64(0.1*size(iris,1)), replace=false).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mbauman/InvertedIndices.jl/issues/19#issuecomment-624233703>,
or unsubscribe

**Comment by mbauman** [comment]
I'm very glad that was it!  You had me worried for a moment. :)
