### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by davidanthoff** [JuliaData/InvertedIndices.jl#3]
Any chance this might be registered? We have a use-case for this in a different package, and it would be nice if we could use the functionality from here.

**Comment by davidanthoff** [comment]
@mbauman Bump, any chance that this might be registered? Really, any reason not to? :) Such a nice little package!

**Comment by colintbowers** [comment]
I've directed a couple of StackOverflow questions to this package... and just had the inevitable case of someone telling me it doesn't work (because they tried to get it via the package manager). So I strongly second that registration would be great for this very useful package.

**Comment by mbauman** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/22107

**Comment by ararslan** [comment]
Hooray! Now to get it into Base. 😉
