### ISSUE TITLE
Indexing with Not(nonexistent_index)

### ISSUE THREAD

**Issue by yurivish** [JuliaData/InvertedIndices.jl#8]
```
[1, 2, 3][Not(4)]
```

To my mind this should return `[1, 2, 3]`, but it throws a puzzling error:

```
BoundsError: attempt to access 3-element Array{Int64,1} at index [[1, 2]]
Stacktrace:
 [1] throw_boundserror(::Array{Int64,1}, ::Tuple{InvertedIndices.InvertedIndexIterator{Int64,Int64,Base.OneTo{Int64}}}) at ./abstractarray.jl:484
 [2] checkbounds at ./abstractarray.jl:449 [inlined]
 [3] _getindex at ./multidimensional.jl:641 [inlined]
 [4] getindex(::Array{Int64,1}, ::InvertedIndex{Int64}) at ./abstractarray.jl:927
 [5] top-level scope at In[16]:1
```

**Comment by mbauman** [comment]
Hah, yeah, that's a bad error message, but the behavior is intentional.  I think to invert an index we should require it to be an in-bounds index in the first place, but I'm open to discussion on this point.

**Comment by yurivish** [comment]
One argument in favor of this is a sparse named array that is modeled as implicitly having all possible names — the real-world example here is [D4M](https://arxiv.org/pdf/1708.02934.pdf) associative arrays, recently expanded upon in a [book](https://mitpress.mit.edu/books/mathematics-big-data). I'm playing around with a Julia implementation, hence my recent spate of questions. 😄 

The core idea is to represent a data table with one array row for each data row, and one array column for each (data column, value) pair, and to be closed under indexing and abstract algebra operations like array multiplication — you can multiply together any two arrays, even if the dimensions don't match, because the semantics are to line them up by name.

The closure properties make this very powerful, and I think dictate that indexing an array with nonexistent indices should in general work and return some sort of empty or zero value.

**Comment by mbauman** [comment]
If the array implicitly has all possible names, then I'd think that `A["nonexistent"]` should be considered in-bounds in the first place.  And if it is, then `A[Not("nonexistent")]` will work just fine.

**Comment by yurivish** [comment]
Woooah. You're right! I implemented a `NonexistentIndex` type that resolves to `[]` as the index for a name not present in the array, and now everything magically works...

**Comment by mbauman** [comment]
I'm going to call this a feature — that the skipped indices must be in-bounds to begin with — and just improve the error messages in #12.
